import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { fetchApi } from '../api';

export default function Settings() {
  const [profile, setProfile] = useState<any>(null);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { fetchApi('/seeker/profile').then(setProfile).catch(e => setError(e.message)); }, []);
  const submitPassword = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); setError(''); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const data = await fetchApi('/auth/password', { method: 'PATCH', body: JSON.stringify(payload) }); setMessage(data.message || 'Password updated'); event.currentTarget.reset(); } catch (e: any) { setError(e.message); } };
  const checks = [['Profile photo', Boolean(profile?.avatarUrl), '/profile'], ['Professional headline', Boolean(profile?.headline || profile?.preferredTitle), '/profile'], ['About section', Boolean(profile?.about), '/profile'], ['Skills', Boolean(profile?.skills), '/profile'], ['Resume', Boolean(profile?.resumeUrl), '/profile'], ['Location', Boolean(profile?.location), '/profile']];
  const completion = profile ? Math.round((checks.filter(item => item[1]).length / checks.length) * 100) : 0;
  return <div className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6">
    <div className="mb-7"><p className="text-sm text-cyan-300">Control center</p><h1 className="mt-1 text-3xl font-bold text-white">Settings</h1><p className="mt-2 text-sm text-zinc-400">Keep your professional profile and account preferences up to date.</p></div>
    {error && <div role="alert" className="mb-5 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
    <div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]">
      <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><h2 className="text-lg font-semibold text-white">Profile checklist</h2><div className="mt-4 flex items-center justify-between text-sm"><span className="text-zinc-400">Profile {completion}% complete</span><Link to="/profile" className="text-cyan-300 hover:underline">Edit profile</Link></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${completion}%` }} /></div><div className="mt-5 space-y-3">{checks.map(([label, done, path]) => <Link key={String(label)} to={String(path)} className="flex items-center justify-between rounded-lg border border-white/5 px-3 py-2.5 text-sm hover:border-cyan-400/30"><span className={done ? 'text-zinc-500 line-through' : 'text-white'}>{String(label)}</span><span className={done ? 'text-emerald-300' : 'text-cyan-300'}>{done ? 'Complete' : 'Add'}</span></Link>)}</div></section>
      <form onSubmit={submitPassword} className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><h2 className="text-lg font-semibold text-white">Security</h2><p className="mt-2 text-sm text-zinc-400">Update your password to keep your account secure.</p>{message && <p role="status" className="mt-4 text-sm text-emerald-300">{message}</p>}<div className="mt-5 space-y-3"><input name="currentPassword" type="password" required placeholder="Current password" className="w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-white outline-none focus:border-cyan-400/60" /><input name="newPassword" type="password" minLength={8} required placeholder="New password" className="w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-white outline-none focus:border-cyan-400/60" /></div><button className="mt-5 rounded-lg bg-cyan-400 px-4 py-2.5 text-xs font-bold uppercase tracking-wider text-black">Update password</button></form>
    </div>
    <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.03] p-6"><h2 className="text-lg font-semibold text-white">Account preferences</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/5 p-4"><p className="text-sm font-medium text-white">Email notifications</p><p className="mt-1 text-xs text-zinc-500">Application and connection updates are enabled.</p></div><div className="rounded-xl border border-white/5 p-4"><p className="text-sm font-medium text-white">Privacy</p><p className="mt-1 text-xs text-zinc-500">Your professional profile is visible to authenticated members.</p></div><div className="rounded-xl border border-white/5 p-4"><p className="text-sm font-medium text-white">Activity</p><p className="mt-1 text-xs text-zinc-500">Review applications, saved jobs, and connections from the dashboard.</p></div></div></section>
  </div>;
}
