import { useState } from 'react';
import { useSearchParams, useNavigate, Link } from 'react-router-dom';
import { fetchApi } from '../api';

export default function VerifyEmail() {
  const [params] = useSearchParams(); const [email, setEmail] = useState(params.get('email') || ''); const [code, setCode] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const navigate = useNavigate();
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await fetchApi('/auth/verify-email', { method: 'POST', body: JSON.stringify({ email, code, token: params.get('token') || undefined }) }); setMessage('Email verified successfully. You can now sign in.'); setTimeout(() => navigate('/login'), 900); } catch (e: any) { setError(e.message); } };
  const resend = async () => { try { const data = await fetchApi('/auth/resend-verification', { method: 'POST', body: JSON.stringify({ email }) }); setMessage(data.message); } catch (e: any) { setError(e.message); } };
  return <div className="flex-1 flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md bg-zinc-900/30 border border-white/5 p-10 space-y-5"><h1 className="text-3xl font-bold text-white">Verify your email</h1><p className="text-sm text-zinc-500">Enter the six-digit code sent to your email. It expires in two minutes.</p>{message && <div className="text-cyan-400 text-sm">{message}</div>}{error && <div className="text-red-400 text-sm">{error}</div>}<label className="block text-xs text-zinc-400">Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} className="w-full mt-2 p-3 bg-zinc-900 text-white" /></label><label className="block text-xs text-zinc-400">Verification code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required={!params.get('token')} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ''))} className="w-full mt-2 p-3 bg-zinc-900 text-white tracking-widest" /></label><button className="w-full bg-cyan-500 text-black py-3 font-bold">VERIFY EMAIL</button><button type="button" onClick={resend} className="w-full border border-white/10 text-zinc-300 py-3">RESEND CODE</button><Link to="/login" className="block text-center text-cyan-400 text-sm">Back to login</Link></form></div>;
}
