import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    unique: true,
    sparse: true,
    lowercase: true,
    trim: true,
    index: true,
  },
  username: {
    type: String,
    required: true,
    unique: true,
    sparse: true,
    lowercase: true,
    trim: true,
    minlength: 3,
    maxlength: 30,
    match: /^[a-z0-9_]+$/,
    index: true,
  },
  passwordHash: {
    type: String,
    required: true,
    select: false,
  },
  role: {
    type: String,
    enum: ['ADMIN', 'SEEKER'],
    default: 'SEEKER',
  },
  emailVerified: { type: Boolean, default: false },
  emailVerifiedAt: { type: Date, default: null },
  verificationCodeHash: { type: String, default: null, select: false },
  verificationCodeExpiresAt: { type: Date, default: null, select: false },
  verificationAttempts: { type: Number, default: 0, select: false },
  lastVerificationCodeSentAt: { type: Date, default: null, select: false },
  emailVerificationTokenHash: { type: String, default: null, select: false },
  emailVerificationExpiresAt: { type: Date, default: null, select: false },
  passwordResetTokenHash: { type: String, default: null, select: false },
  passwordResetExpiresAt: { type: Date, default: null, select: false },
  passwordResetCodeHash: { type: String, default: null, select: false },
  passwordResetCodeExpiresAt: { type: Date, default: null, select: false },
  passwordResetAttempts: { type: Number, default: 0, select: false },
  lastPasswordResetCodeSentAt: { type: Date, default: null, select: false },
  tokenVersion: { type: Number, default: 0 },
  lastLoginAt: { type: Date, default: null },
  loginOtpHash: { type: String, default: null, select: false },
  loginOtpExpiresAt: { type: Date, default: null, select: false },
  loginOtpAttempts: { type: Number, default: 0, select: false },
  lastLoginCodeSentAt: { type: Date, default: null, select: false },
  notificationPreferences: { type: mongoose.Schema.Types.Mixed, default: {} },
  privacySettings: { type: mongoose.Schema.Types.Mixed, default: {} },
  deactivatedAt: { type: Date, default: null },
}, {
  timestamps: true,
});

export const User = mongoose.model('User', userSchema);
